package MortgageRule

import com.example.mortgage.model.*;
import com.example.mortgage.digest.*;
import java.util.*;

dialect "java"

// -- Debug --
rule "Print loan"
  when
    anObject: MortgageLoan()
  then
    System.out.println("Print loan = " + anObject);
end

rule "Print MortgageLoanDigest"
  when
    anObject: MortgageLoanDigest()
  then
    System.out.println("Print MortgageLoanDigest = " + anObject);
end

rule "Print LoanOfficer"
  when
    anObject: LoanOfficer()
  then
    System.out.println("Print LoanOfficer = " + anObject);
end

rule "Print LoanOfficerDigest"
  when
    anObject: LoanOfficerDigest()
  then
    System.out.println("Print LoanOfficerDigest = " + anObject);
end

rule "Print Customer"
  when
    anObject: Customer()
  then
    System.out.println("Print Customer = " + anObject);
end

rule "Print CustomerDigest"
  when
    anObject: CustomerDigest()
  then
    System.out.println("Print CustomerDigest = " + anObject);
end

// -- Validation --

rule "Invalid Loan Officer"
  when
    not LoanOfficerDigest()
  then
    System.out.println("Invalid Loan Officer");
    insert(MortgageLoanStatus.LOAN_OFFICER_INCOMPLETE);
end

rule "CustomerDigest missing first name"
  when
    $c : CustomerDigest(firstName == null || firstName.trim().isEmpty())
  then
    System.out.println("CustomerDigest missing first name");
    insert(MortgageLoanStatus.USER_INFO_INCOMPLETE);
end

rule "CustomerDigest missing last name"
  when
    $c : CustomerDigest(lastName == null || lastName.trim().isEmpty())
  then
    System.out.println("CustomerDigest missing last name");
    insert(MortgageLoanStatus.USER_INFO_INCOMPLETE);
end

rule "CustomerDigest missing phone"
  when
    $c : CustomerDigest(phone == null || phone.trim().isEmpty())
  then
    System.out.println("CustomerDigest missing phone");
    insert(MortgageLoanStatus.USER_INFO_INCOMPLETE);
end

rule "CustomerDigest missing email"
  when
    $c : CustomerDigest(email == null || email.trim().isEmpty())
  then
    System.out.println("CustomerDigest missing email");
    insert(MortgageLoanStatus.USER_INFO_INCOMPLETE);
end

// -- Business rules --
rule "Set MortgageLoanStatus"
  when
    $status: MortgageLoanStatus()
    $loan: MortgageLoan()
  then
    System.out.println("Set MortgageLoanStatus " + $status);
    $loan.setStatusEnum($status);
end
